-- Blockstorm friends-only private chat migration.

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 120),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create index if not exists private_messages_conversation_idx
  on public.private_messages(sender_id,recipient_id,created_at desc);
create index if not exists private_messages_recipient_idx
  on public.private_messages(recipient_id,created_at desc);

alter table public.private_messages enable row level security;
revoke all on public.private_messages from anon,authenticated;

create or replace function public.send_private_message(p_friend_id uuid,p_message text)
returns void language plpgsql security definer set search_path=''
as $$
declare v_message text:=trim(p_message);
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_friend_id is null or p_friend_id=auth.uid() then raise exception '無效的私訊對象'; end if;
  if v_message is null or char_length(v_message) not between 1 and 120 then raise exception '訊息需要 1–120 個字'; end if;
  if not exists(
    select 1 from public.friendships
    where status='accepted'
      and auth.uid() in(user_a,user_b)
      and p_friend_id in(user_a,user_b)
  ) then raise exception '只能與好友私聊'; end if;
  insert into public.private_messages(sender_id,recipient_id,message)
  values(auth.uid(),p_friend_id,v_message);
end;
$$;

create or replace function public.get_private_messages(p_friend_id uuid)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_messages jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not exists(
    select 1 from public.friendships
    where status='accepted'
      and auth.uid() in(user_a,user_b)
      and p_friend_id in(user_a,user_b)
  ) then raise exception '只能查看好友私訊'; end if;

  select coalesce(jsonb_agg(to_jsonb(conversation) order by conversation.created_at),'[]'::jsonb)
  into v_messages
  from (
    select m.id,m.sender_id,m.recipient_id,m.message,m.created_at,p.username,p.avatar
    from public.private_messages m
    join public.profiles p on p.id=m.sender_id
    where (m.sender_id=auth.uid() and m.recipient_id=p_friend_id)
       or (m.sender_id=p_friend_id and m.recipient_id=auth.uid())
    order by m.created_at desc
    limit 80
  ) conversation;
  return v_messages;
end;
$$;

revoke execute on function public.send_private_message(uuid,text) from public,anon;
revoke execute on function public.get_private_messages(uuid) from public,anon;
grant execute on function public.send_private_message(uuid,text) to authenticated;
grant execute on function public.get_private_messages(uuid) to authenticated;
