-- Blockstorm four-player private rooms and lobby chat.
-- Run after cosmetics_v2.sql.

alter table public.match_rooms add column if not exists max_players integer not null default 4 check (max_players between 2 and 4);
alter table public.match_rooms add column if not exists settings jsonb not null default '{"balance":true,"target_mode":"random","garbage_delay":1200}'::jsonb;

create table if not exists public.room_members (
  room_id uuid not null references public.match_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  peer_id text not null,
  ready boolean not null default false,
  handicap_rows integer not null default 0 check (handicap_rows between 0 and 6),
  joined_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.lobby_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 120),
  created_at timestamptz not null default now()
);

alter table public.room_members enable row level security;
alter table public.lobby_messages enable row level security;
revoke all on public.room_members from anon,authenticated;
revoke all on public.lobby_messages from anon,authenticated;

create or replace function public.party_room_payload(p_room_id uuid)
returns jsonb language sql security definer set search_path='' as $$
  select jsonb_build_object(
    'state',case when r.status='playing' then 'playing' else 'lobby' end,
    'room_id',r.id,'code',r.code,'host_id',r.host_id,'host_peer_id',r.host_peer_id,
    'max_players',r.max_players,'settings',r.settings,'is_private',true,
    'members',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',m.user_id,'username',p.username,'avatar',p.avatar,'rating',p.rating,
        'peer_id',m.peer_id,'ready',m.ready,'handicap_rows',m.handicap_rows
      ) order by m.joined_at)
      from public.room_members m join public.profiles p on p.id=m.user_id where m.room_id=r.id
    ),'[]'::jsonb)
  ) from public.match_rooms r where r.id=p_room_id;
$$;

create or replace function public.create_party_room(p_peer_id text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_room public.match_rooms;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if nullif(trim(p_peer_id),'') is null then raise exception 'Peer ID required'; end if;
  delete from public.matchmaking_queue where user_id=auth.uid();
  update public.match_rooms set status='cancelled',updated_at=now() where host_id=auth.uid() and status='waiting';
  insert into public.match_rooms(code,host_id,host_peer_id,is_private,status,max_players,settings)
  values(upper(substr(replace(gen_random_uuid()::text,'-',''),1,6)),auth.uid(),trim(p_peer_id),true,'waiting',4,
    '{"balance":true,"target_mode":"random","garbage_delay":1200}'::jsonb) returning * into v_room;
  insert into public.room_members(room_id,user_id,peer_id,ready) values(v_room.id,auth.uid(),trim(p_peer_id),true);
  return public.party_room_payload(v_room.id);
end;$$;

create or replace function public.join_party_room(p_code text,p_peer_id text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_room public.match_rooms;v_count integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into v_room from public.match_rooms where code=upper(trim(p_code)) and status='waiting' and is_private=true order by created_at desc limit 1 for update;
  if v_room.id is null then raise exception '找不到可加入的房間'; end if;
  select count(*) into v_count from public.room_members where room_id=v_room.id;
  if v_count>=v_room.max_players and not exists(select 1 from public.room_members where room_id=v_room.id and user_id=auth.uid()) then raise exception '房間已滿'; end if;
  insert into public.room_members(room_id,user_id,peer_id,ready) values(v_room.id,auth.uid(),trim(p_peer_id),false)
  on conflict(room_id,user_id) do update set peer_id=excluded.peer_id,ready=false,joined_at=now();
  return public.party_room_payload(v_room.id);
end;$$;

create or replace function public.get_party_room(p_room_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  if not exists(select 1 from public.room_members where room_id=p_room_id and user_id=auth.uid()) then raise exception '你不在這個房間'; end if;
  return public.party_room_payload(p_room_id);
end;$$;

create or replace function public.update_party_settings(p_room_id uuid,p_max_players integer,p_settings jsonb,p_handicaps jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare pair record;v_count integer;
begin
  if not exists(select 1 from public.match_rooms where id=p_room_id and host_id=auth.uid() and status='waiting') then raise exception '只有房主能修改設定'; end if;
  select count(*) into v_count from public.room_members where room_id=p_room_id;
  if p_max_players<greatest(2,v_count) or p_max_players>4 then raise exception '人數上限不正確'; end if;
  update public.match_rooms set max_players=p_max_players,settings=jsonb_build_object(
    'balance',coalesce((p_settings->>'balance')::boolean,true),
    'target_mode',case when p_settings->>'target_mode'='rotate' then 'rotate' else 'random' end,
    'garbage_delay',least(1600,greatest(800,coalesce((p_settings->>'garbage_delay')::integer,1200)))
  ),updated_at=now() where id=p_room_id;
  for pair in select key,value from jsonb_each_text(coalesce(p_handicaps,'{}'::jsonb)) loop
    update public.room_members set handicap_rows=least(6,greatest(0,pair.value::integer)) where room_id=p_room_id and user_id=pair.key::uuid;
  end loop;
  return public.party_room_payload(p_room_id);
end;$$;

create or replace function public.set_party_ready(p_room_id uuid,p_ready boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  update public.room_members set ready=case when user_id=(select host_id from public.match_rooms where id=p_room_id) then true else p_ready end where room_id=p_room_id and user_id=auth.uid();
  if not found then raise exception '你不在這個房間'; end if;
  return public.party_room_payload(p_room_id);
end;$$;

create or replace function public.start_party_room(p_room_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_count integer;v_unready integer;
begin
  if not exists(select 1 from public.match_rooms where id=p_room_id and host_id=auth.uid() and status='waiting') then raise exception '只有房主能開始遊戲'; end if;
  select count(*),count(*) filter(where not ready) into v_count,v_unready from public.room_members where room_id=p_room_id;
  if v_count<2 then raise exception '至少需要 2 位玩家'; end if;
  if v_unready>0 then raise exception '還有玩家尚未準備'; end if;
  update public.match_rooms set status='playing',updated_at=now() where id=p_room_id;
  return public.party_room_payload(p_room_id);
end;$$;

create or replace function public.leave_party_room(p_room_id uuid)
returns void language plpgsql security definer set search_path='' as $$
begin
  if exists(select 1 from public.match_rooms where id=p_room_id and host_id=auth.uid()) then
    update public.match_rooms set status=case when status='waiting' then 'cancelled' else 'finished' end,updated_at=now() where id=p_room_id;
  else delete from public.room_members where room_id=p_room_id and user_id=auth.uid();
  end if;
end;$$;

create or replace function public.send_lobby_message(p_message text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if char_length(trim(p_message)) not between 1 and 120 then raise exception '訊息長度需為 1–120 字'; end if;
  insert into public.lobby_messages(user_id,message) values(auth.uid(),trim(p_message));
  delete from public.lobby_messages where created_at<now()-interval '7 days';
end;$$;

create or replace function public.get_lobby_messages()
returns jsonb language sql security definer set search_path='' as $$
  select coalesce(jsonb_agg(x order by x.created_at),'[]'::jsonb) from (
    select m.id,m.user_id,p.username,p.avatar,m.message,m.created_at
    from public.lobby_messages m join public.profiles p on p.id=m.user_id order by m.id desc limit 60
  ) x;
$$;

revoke execute on function public.party_room_payload(uuid) from public,anon,authenticated;
revoke execute on function public.create_party_room(text) from public,anon;
revoke execute on function public.join_party_room(text,text) from public,anon;
revoke execute on function public.get_party_room(uuid) from public,anon;
revoke execute on function public.update_party_settings(uuid,integer,jsonb,jsonb) from public,anon;
revoke execute on function public.set_party_ready(uuid,boolean) from public,anon;
revoke execute on function public.start_party_room(uuid) from public,anon;
revoke execute on function public.leave_party_room(uuid) from public,anon;
revoke execute on function public.send_lobby_message(text) from public,anon;
revoke execute on function public.get_lobby_messages() from public,anon;
grant execute on function public.create_party_room(text),public.join_party_room(text,text),public.get_party_room(uuid),public.update_party_settings(uuid,integer,jsonb,jsonb),public.set_party_ready(uuid,boolean),public.start_party_room(uuid),public.leave_party_room(uuid),public.send_lobby_message(text),public.get_lobby_messages() to authenticated;
