/* Presentation-only bilingual labels. Game-owned text remains untouched. */
(() => {
  const labels = {
"新星":"ROOKIE", "青銅":"BRONZE", "白銀":"SILVER", "黃金":"GOLD", "白金":"PLATINUM", "鑽石":"DIAMOND", "大師":"MASTER", "選擇頭像":"AVATAR",
  "登入": "LOG IN",
  "創建帳號": "SIGN UP",
  "帳號設定": "ACCOUNT",
  "登出": "LOG OUT",
  "不登入，先進入離線練習": "OFFLINE PRACTICE",
  "編輯": "EDIT",
  "開始遊戲": "PLAY",
  "一般配對": "CASUAL",
  "牌位競技": "RANKED",
  "單人模式": "SOLO",
  "好友房間": "PRIVATE",
  "開始配對": "MATCH",
  "牌位配對": "RANK UP",
  "建立房間": "CREATE",
  "加入": "JOIN",
  "排行榜": "RANKINGS",
  "全球排行": "GLOBAL",
  "好友排行": "FRIENDS",
  "好友與邀請": "SOCIAL",
  "加入好友": "ADD FRIEND",
  "等待你回覆": "REQUESTS",
  "所有好友": "FRIEND LIST",
  "聊天中心": "COMMS",
  "公共聊天": "PUBLIC",
  "好友私聊": "PRIVATE",
  "傳送": "SEND",
  "好友": "FRIENDS",
  "造型商店": "ARSENAL",
  "方塊造型": "BLOCK SKINS",
  "遊戲背板": "BACKDROPS",
  "任務與成就": "MISSIONS",
  "每日": "DAILY",
  "主線": "STORY",
  "成就": "ACHIEVEMENTS",
  "一鍵領取": "CLAIM ALL",
  "遊戲大廳": "LOBBY",
  "商店": "SHOP",
  "任務": "MISSIONS",
  "聊天": "COMMS",
  "離開房間": "LEAVE",
  "玩家": "PLAYERS",
  "邀請好友": "INVITE",
  "房間設定": "ROOM CONFIG",
  "房間聊天": "ROOM COMMS",
  "我已準備": "READY",
  "取消準備": "NOT READY",
  "等待對手加入": "STAND BY",
  "找到對手": "MATCH FOUND",
  "取消並返回": "BACK",
  "勝利": "VICTORY",
  "落敗": "DEFEAT",
  "本局結束": "RUN COMPLETE",
  "再來一場": "PLAY AGAIN",
  "結束並回大廳": "RETURN",
  "回到大廳": "LOBBY",
  "個人資料": "PLAYER ID",
  "儲存設定": "SAVE",
  "取消": "CANCEL",
  "接受": "ACCEPT",
  "略過": "SKIP",
  "停止配對": "CANCEL",
  "使用中": "EQUIPPED",
  "套用造型": "EQUIP",
  "未解鎖": "LOCKED",
  "已領取": "CLAIMED",
  "領取": "CLAIM",
  "進行中": "IN PROGRESS",
  "已是好友": "CONNECTED",
  "邀請已送出": "REQUEST SENT",
  "邀請": "INVITE",
  "已邀請": "INVITED",
  "邀請對戰": "CHALLENGE",
  "查看": "VIEW",
  "暫停": "PAUSED",
  "正在尋找牌位對手": "RANKED SEARCH",
  "正在尋找對手": "SEARCHING",
  "單人練習": "PRACTICE",
  "私人對戰": "PRIVATE MATCH",
  "好友多人對戰": "PARTY MATCH",
  "霓虹經典": "NEON",
  "街機糖果": "ARCADE",
  "冰晶藍": "ICE",
  "黑白極簡": "MONO",
  "落日餘暉": "SUNSET",
  "翡翠森林": "FOREST",
  "熔岩核心": "MAGMA",
  "皇家星塵": "ROYAL",
  "奶霜珍珠": "PEARL",
  "櫻花和菓": "SAKURA",
  "深海微光": "OCEAN",
  "薰衣草霧": "LAVENDER",
  "赤銅工坊": "COPPER",
  "薄荷玻璃": "MINT",
  "深空競技場": "VOID",
  "極光脈衝": "AURORA",
  "冰晶宮殿": "GLACIER",
  "暮色都市": "SUNSET CITY",
  "翡翠遺跡": "FOREST RUINS",
  "熔岩地心": "MAGMA CORE",
  "皇家星雲": "ROYAL NEBULA",
  "亞麻棋盤": "LINEN",
  "紙境庭園": "PAPER GARDEN",
  "雨夜窗景": "RAIN WINDOW",
  "暮色沙丘": "DUNES",
  "月下靜湖": "MOON LAKE",
  "完成一場對戰": "FIRST CONTACT",
  "消除 10 行": "CLEAR TEN",
  "今日累積 5,000 分": "SCORE RUN",
  "贏得一場對戰": "TAKE THE WIN",
  "踏入風暴": "ENTER THE STORM",
  "開始整理": "CLEAN SWEEP",
  "分數起飛": "LIFT OFF",
  "初露鋒芒": "FIRST STRIKE",
  "方塊清道夫": "BLOCK CLEANER",
  "掌握節奏": "FIND THE RHYTHM",
  "四行攻勢": "QUAD STRIKE",
  "六位數玩家": "SIX FIGURES",
  "十勝之路": "TEN VICTORIES",
  "風暴之眼": "STORM EYE",
  "分數萌芽": "SCORE SEED",
  "分數突破 I": "BREAKTHROUGH I",
  "分數突破 II": "BREAKTHROUGH II",
  "分數突破 III": "BREAKTHROUGH III",
  "接續消除": "CHAIN START",
  "連鎖反應": "CHAIN REACTION",
  "風暴連鎖": "STORM CHAIN",
  "無間連鎖": "ENDLESS CHAIN",
  "第一次四消": "FIRST QUAD",
  "四行專家": "QUAD EXPERT",
  "四行大師": "QUAD MASTER",
  "完美無瑕": "FLAWLESS",
  "完美主義": "PERFECTION",
  "熟悉戰場": "BATTLE READY",
  "百戰前夕": "VETERAN"
};
  const selector = 'h2:not(#playerModalTitle), h3, button:not(#authSubmit):not([data-lobby-view]):not(.private-friend), #authSubmit > span, .lobby-dock b, #overlayTitle, #matchmakingToastTitle, #matchMode, #profileRank, #dailyMissionTitle, .setting-label';
  function update() {
    document.querySelectorAll(selector).forEach(el => {
      if (el.closest('.chat-messages, .party-members, .leaderboard-player')) return;
      const key = el.textContent.replace(/[→＋]/g, '').replace(/\s+/g, ' ').trim();
      const en = (el.id === 'dailyMissionTitle' ? 'DAILY OPS' : labels[key]) || (el.id === 'matchMode' && key.startsWith('單人模式') ? 'SOLO' : '');
      if (en) el.dataset.en = en;
      else delete el.dataset.en;
    });
  }
  update();
  let queued = false;
  new MutationObserver(() => {
    if (queued) return;
    queued = true;
    requestAnimationFrame(() => { queued = false; update(); });
  }).observe(document.body, { childList: true, characterData: true, subtree: true });
})();
